[package]
name = "genesis-gf"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
ed25519-dalek = "0.6.2"
sha2 = "0.7"
bs58 = "0.2.0"
base32 = "0.3.1"
mtdparts = "0.1"
